name: CommandShield
version: 1.1
main: com.commandshield.CommandShield
api-version: 1.20
description: Blocks the /gamerule randomtickspeed command
author: ItsJustNickDev

commands:
  cshield:
    description: Manage blocked commands.
    usage: /cshield <add|remove|list|help> <command>
    aliases: [cshield]