name: Build and Release JAR

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn clean package

    - name: Verify JAR file location
      run: |
        echo "Checking for JAR file at target/"
        ls -lh target/  # List files in the target directory to confirm the JAR file exists

  release:
    needs: build
    runs-on: ubuntu-latest
     
     

    steps:
    - name: Check downloaded artifact
      run: ls -lh ./
      
    - name: Checkout repository (again for release step)
      uses: actions/checkout@v4

    - name: Create GitHub Release and upload artifact
      uses: softprops/action-gh-release@v2
      with:
        files: target/commandshield-1.0-SNAPSHOT.jar  # Correct path to your JAR file
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for ${{ github.ref_name }}.
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

